# Generated by Django 4.2.1 on 2023-05-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_todo_completed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todo",
            name="date_completed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
